Repository GeoNode/geonode-project, pull requests merged in 2022-07, with the labels that each got.

#343 [Fixes #342] Geoserver Dockerfile, build failed
  docker/geoserver/Dockerfile
Labels: backport 4.x, backport 3.3.x

#347 - Bump GeoServer to version 2.20.5
  .env.sample
  dev_config.yml
  docker-compose.yml
  docker/geoserver/Dockerfile
  docker/geoserver/docker-compose.yml
  geonode-stack.yml
  playbook.yml
  src/dev_config.yml
Labels: dependencies, 4.x, backport 4.x

#348 [Backport to 4.x] Bump geoserver 2.20.5 4.x
  .env.sample
  dev_config.yml
  docker-compose.yml
  docker/geoserver/Dockerfile
  docker/geoserver/docker-compose.yml
  geonode-stack.yml
  playbook.yml
  src/dev_config.yml
Labels: dependencies

#349 Aligning docker-compose with the geonode one
  .env.sample
  docker-compose.yml
Labels: 4.x, backport 4.x

#350 [Backport to 4.x] Aligning docker-compose with the geonode one
  .env.sample
  docker-compose.yml
Labels: 4.x

#359 [Fixes #358] fix renaming of CORS_ORIGIN_ALLOW_ALL
  .env.sample
  .override_dev_env.sample
Labels: backport 4.x, backport 3.3.x
